# Defaults and Usage
#
# =============
# allowDispensers: true
# 
# Allow dispenser arrows to activate Bullseye signs.
# If true, any message on lines 2-4 of the sign is not displayed.
#
# =============
# allowSkeletons: false
# 
# Allow skeletons to activate Bullseye signs.
# If true, any message on lines 2-4 of the sign is not displayed.
#
# =============
# blockList:
#   blacklist: true
#   blocks:
#   - BEDROCK
# 
# blockList determines which blocks can/can't be used as a Bullseye block (the
# block you put a Bullseye sign on).
# 
# > blacklist: true = exclude these blocks
#              false = makes it a whitelist/allow ONLY these blocks
# 
# > blocks: list of blocks to be used as a blacklist/whitelist. Use Bukkit
#           standard names.

allowDispensers: true
allowSkeletons: false
blockList:
  blacklist: true
  blocks:
  - BEDROCK