# Defaults and Usage
#
# =============
# allowDispensers: true
# 
# Allow dispenser arrows to activate Bullseye signs.
# If true, any message on lines 2-4 of the sign is not displayed.
#
# =============
# allowSkeletons: false
# 
# Allow skeletons to activate Bullseye signs.
# If true, any message on lines 2-4 of the sign is not displayed.
#
# =============
# maxActiveTicks: 100
#
# Maximum time a sign will be activated for, in ticks.
# If a signs' tag ends with a number, it will activate for that long, up to this value.
#
# =============
# blockList:
#   type: deny
#   blocks:
#   - BEDROCK
# 
# blockList determines which blocks can/can't be used as a Bullseye block (the block you put a Bullseye sign on).
# 
# > type: deny  = allow all blocks EXCEPT these blocks
#         allow = allow ONLY these blocks
# 
# > blocks: list of block names. Use Bukkit standard names. https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html

allowDispensers: true
allowSkeletons: false
maxActiveTicks: 100
blockList:
  type: deny
  blocks:
  - BEDROCK